import { BoxInfo } from './boxInfo';

export const Oficina: BoxInfo[] = [
  {
    idBox: 'boxOeste',
    tituloBox: 'Oficina Oeste',
    calidadAireActual: 'buena',
    humedadActual: 50,
    luminosidadActual: 500,
    ruidoActual: 30,
    temperaturaActual: 30,
    detallesAire: {
      dioxidoAzufre: 500,
      dioxidoNitrogeno: 200,
      ozono: 100,
      particulasFinas: 600,
      particulasRespirables: 1000,
    },
  },
  {
    idBox: 'boxNorte',
    tituloBox: 'Oficina Norte',
    calidadAireActual: 'buena',
    humedadActual: 50,
    luminosidadActual: 500,
    ruidoActual: 30,
    temperaturaActual: 30,
    detallesAire: {
      dioxidoAzufre: 500,
      dioxidoNitrogeno: 200,
      ozono: 100,
      particulasFinas: 600,
      particulasRespirables: 1000,
    },
  },
  {
    idBox: 'boxPlaza',
    tituloBox: 'Plaza',
    calidadAireActual: 'buena',
    humedadActual: 50,
    luminosidadActual: 500,
    ruidoActual: 30,
    temperaturaActual: 30,
    detallesAire: {
      dioxidoAzufre: 500,
      dioxidoNitrogeno: 200,
      ozono: 100,
      particulasFinas: 600,
      particulasRespirables: 1000,
    },
  },
  {
    idBox: 'boxSur',
    tituloBox: 'Oficina Sur',
    calidadAireActual: 'buena',
    humedadActual: 50,
    luminosidadActual: 500,
    ruidoActual: 30,
    temperaturaActual: 30,
    detallesAire: {
      dioxidoAzufre: 500,
      dioxidoNitrogeno: 200,
      ozono: 100,
      particulasFinas: 600,
      particulasRespirables: 1000,
    },
  },
  {
    idBox: 'boxEste',
    tituloBox: 'Oficina Este',
    calidadAireActual: 'mala',
    humedadActual: 50,
    luminosidadActual: 500,
    ruidoActual: 30,
    temperaturaActual: 30,
    detallesAire: {
      dioxidoAzufre: 500,
      dioxidoNitrogeno: 200,
      ozono: 100,
      particulasFinas: 600,
      particulasRespirables: 1000,
    },
  },
];
